apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-backend-image
          ports:
            - containerPort: 3000
          env:
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672
            - name: DATABASE_URL
              value: postgres://clinic:password@postgres:5432/booking
---
