apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: your-worker-image
          env:
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672
            - name: DATABASE_URL
              value: postgres://clinic:password@postgres:5432/booking
